---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar-pca9685-pwm
data:
  ############################
  # STEERING PWM - PCA9685   #
  ############################
  STEERING_PCA9685_LEFT_PWM: "995"
  STEERING_PCA9685_RIGHT_PWM: "2017"
  STEERING_PCA9685_CENTER_PWM: "1440"

  ###########################
  # THROTTLE PWM - PCA9685  #
  ############################
  THROTTLE_PCA9685_MIN_PWM: "994"
  THROTTLE_PCA9685_MAX_PWM: "1975"
  THROTTLE_PCA9685_ZERO_PWM: "1420"

