---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robocar

resources:
  - ../common
  - deployments.yaml
  - configmap.yaml

images:
  - name: docker.io/cyrilix/robocar-camera
    newTag: v0.3.0

  - name: docker.io/cyrilix/robocar-pca9685
    newTag: v0.6.4

  - name: docker.io/cyrilix/robocar-oak-camera
    newTag: v0.2.0