---

- name: Copy docker-compose env file
  template:
    src: env
    dest: /home/pi/.env

- name: Copy stack file
  copy:
    src: "{{ item }}"
    dest: /home/pi/
  with_items:
    - docker-compose.yaml
    - simulator-compose.yaml
    - car.yaml
    - robocar.yaml
    - simulator.yaml
