---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robocar

resources:
  - ../common
  - deployments.yaml
  - configmap.yaml

images:
  - name: docker.io/cyrilix/robocar-simulator
    newTag: v0.3.0
