---
- name: Download k3s binary
  get_url:
    url: "{{ k3s_url}}"
    dest: "/usr/local/bin/k3s"
    mode: 0755
    force: yes

- name: Copy systemd script
  template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
  notify: restart k3s

- name: Ensure k3s service is started
  systemd:
    name: k3s
    enabled: yes
    daemon_reload: yes
    state: started
