" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark
colorscheme desert

"" Numérotation des lignes
set nu

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" formattage auto du xml
au FileType xml setlocal equalprg="XMLLINT_INDENT=4 xmllint\ --format\ --recover\ -\ 2>/dev/null"

" remplacement des tabulations par des espaces
set expandtab
set tabstop=4
" To change the number of space characters inserted for indentation, use the 'shiftwidth' option:
set shiftwidth=4
