apiVersion: v1
kind: ConfigMap
metadata:
  name: nats
data:
  standalone.conf: |
    server_name: nats
    http: 0.0.0.0:8222
    jetstream {
      store_dir: /data/datastore
    }
    mqtt {
      listen: 0.0.0.0:1883
    }
    authorization: {
        user: satanas,
        password: satanas
    }