---

- hosts: car
  become: yes
  roles:
    - { role: base, tags: [base]}

- hosts: microservice
  become: yes
  roles:
    - { role: k3s, tags: [k3s] }
    - { role: microservices, tags: [microservices, ms] }
