---

- hosts: car
  become: yes
  roles:
    - { role: base, tags: [base]}

- hosts: microservice
  become: yes
  roles:
    - { role: rabbitmq, tags: [rabbitmq] }
    - { role: k3s, tags: [k3s] }
    - { role: microservices, tags: [microservices, ms] }


- hosts: donkey
  become: yes
  roles:
    - { role: python, tags: [python]}
    - { role: donkey, tags: [donkey] }
