apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar
data:
  # Broker configuration
  MQTT_BROKER_HOST: mqtt.robocar.svc.cluster.local
  MQTT_BROKER: "tcp://mqtt.robocar.svc.cluster.local:1883"

  # Camera
  MQTT_TOPIC_CAMERA: car/satanas/part/camera/color
  MQTT_TOPIC_CAMERA_OAK_COLOR: car/satanas/part/camera/color


  # Radio command
  MQTT_TOPIC_RC_THROTTLE: car/satanas/part/rc/throttle
  MQTT_TOPIC_RC_STEERING: car/satanas/part/rc/steering
  MQTT_TOPIC_RC_SWITCH_RECORD: car/satanas/part/rc/switch_record
  MQTT_TOPIC_RC_DRIVE_MODE: car/satanas/part/rc/drive_mode


  MQTT_TOPIC_TF_STEERING: car/satanas/part/tflite/steering

  # Values to apply
  MQTT_TOPIC_THROTTLE: car/satanas/part/throttle
  MQTT_TOPIC_STEERING: car/satanas/part/steering

  # Road detection
  MQTT_TOPIC_ROAD: car/satanas/part/road

  # Records topic
  MQTT_TOPIC_RECORDS: car/satanas/part/records

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar-throttle
data:
  ############
  # Throttle #
  ############
  # Min value to start is 0.12
  # Good value for manual: 0.15
  #THROTTLE_MIN: "0.15"
  #THROTTLE_MAX: "0.15"

  THROTTLE_MIN: "0.19"
  THROTTLE_MAX: "0.19"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar-steering-pwm
data:
  ################
  # STEERING PWM #
  ################
  STEERING_LEFT_PWM: "1002"
  STEERING_RIGHT_PWM: "1985"
  STEERING_CENTER_PWM: "1491"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar-throttle-pwm
data:
  ################
  # THROTTLE PWM #
  ################
  #THROTTLE_MIN_PWM: "1092"
  #THROTTLE_MAX_PWM: "1986"
  #THROTTLE_ZERO_PWM: "1583"
  THROTTLE_MIN_PWM: "960"
  THROTTLE_MAX_PWM: "1949"
  THROTTLE_ZERO_PWM: "1452"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar-camera
data:
  ##########
  # Camera #
  ##########
  2CAMERA_WIDTH: "160"
  2CAMERA_HEIGHT: "128"

  CAMERA_WIDTH: "160"
  CAMERA_HEIGHT: "120"

  MQTT_CAMERA_PUB_FREQUENCY: "30"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar-models
data:
  # model to use for steering
  MODEL_STEERING: model_categorical_160x120h0_edgetpu.tflite
  #MODEL_STEERING: model_categorical_160x120h0_edgetpu.tflite

  #MODEL_STEERING: model_linear_160x120h40_edgetpu.tflite


  #MODEL_STEERING: model_linear_160x120h20_edgetpu.tflite
  #MODEL_STEERING: model_categorical_160x120h20_edgetpu.tflite


  #MODEL_STEERING: model_linear_160x120h50_edgetpu.tflite

  MODEL_IMAGE_WIDTH: "160"
  MODEL_IMAGE_HEIGHT: "120"
  HORIZON: "20"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: robocar-road
data:
  HORIZON: "20"
